apiVersion: v2
name: web
description: Pre-paid Health Plan Onboarding Portal Web Frontend
type: application
version: 1.0.0
appVersion: 1.0.0

# Keywords for chart discovery and categorization
keywords:
  - web
  - frontend
  - react
  - health-portal

# Chart maintainers
maintainers:
  - name: AUSTA Health
    email: devops@austa.health

# Helm version requirements
kubeVersion: ">=1.21.0"

# Chart dependencies
dependencies:
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled
  - name: cert-manager
    version: v1.12.3
    repository: https://charts.jetstack.io
    condition: ingress.tls.enabled

# Chart annotations
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: "MIT"

# Engine requirements
engine: ">=3.12.0"

# Home URL for the application
home: https://austa.health

# Sources
sources:
  - https://github.com/austa/health-portal

# Icon URL for the chart
icon: https://austa.health/icons/logo.png