version: 2
updates:
  # Frontend (React SPA) dependencies
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
      - "security"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
          - "react-query"
          - "react-router*"
        exclude-patterns:
          - "react-native*"
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "cypress"

  # Backend (Node.js) dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
      - "security"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
      testing:
        patterns:
          - "jest*"
          - "@types/jest"
          - "supertest"
      security:
        patterns:
          - "helmet"
          - "cors"
          - "jsonwebtoken"
          - "bcrypt"
      monitoring:
        patterns:
          - "newrelic"
          - "datadog*"
          - "jaeger*"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Infrastructure (Terraform) dependencies
  - package-ecosystem: "terraform"
    directory: "/infrastructure/terraform"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
      - "infrastructure"
      - "security"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"