# Elasticsearch Configuration (v8.10.0)
# Production configuration for AUSTA Health Plan Onboarding Portal

#----------------------- Cluster Settings -----------------------
cluster.name: austa-health-logs
cluster.initial_master_nodes: ["${HOSTNAME}"]
discovery.seed_hosts: ["elasticsearch-0.elasticsearch-headless", "elasticsearch-1.elasticsearch-headless", "elasticsearch-2.elasticsearch-headless"]
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: "85%"
cluster.routing.allocation.disk.watermark.high: "90%"
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.enable: all
cluster.routing.rebalance.enable: all

#----------------------- Node Settings -------------------------
node.name: ${HOSTNAME}
node.roles: ["master", "data", "ingest"]
node.master: true
node.data: true
node.ingest: true
node.max_local_storage_nodes: 1
node.attr.zone: ${NODE_ZONE}

#----------------------- Paths --------------------------------
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
path.repo: /usr/share/elasticsearch/snapshots

#----------------------- Network Settings ---------------------
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "https://kibana.austa-health.com"
http.cors.allow-headers: "X-Requested-With,Content-Type,Content-Length,Authorization"
http.cors.allow-credentials: true
http.max_content_length: "100mb"

#----------------------- Security Settings -------------------
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12

# Audit Settings
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.include: [
    "authentication_success",
    "authentication_failure",
    "access_denied",
    "connection_denied",
    "index_access_denied",
    "cluster_access_denied",
    "run_as_denied",
    "system_access_denied"
]
xpack.security.audit.logfile.events.emit_request_body: true
xpack.security.authc.api_key.enabled: true
xpack.security.authc.token.enabled: true
xpack.security.authc.realms.native.native1.order: 0

#----------------------- Monitoring Settings -----------------
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
xpack.monitoring.collection.interval: "15s"
xpack.monitoring.history.duration: "7d"
xpack.monitoring.collection.cluster.stats.timeout: "10s"
xpack.monitoring.collection.node.stats.timeout: "10s"
xpack.monitoring.collection.index.stats.timeout: "10s"

#----------------------- Memory Settings --------------------
bootstrap.memory_lock: true
indices.memory.index_buffer_size: "30%"
indices.queries.cache.size: "15%"
indices.fielddata.cache.size: "20%"
indices.breaker.total.use_real_memory: true
indices.breaker.request.limit: "70%"
indices.breaker.fielddata.limit: "60%"

#----------------------- Index Settings --------------------
action.auto_create_index: ".monitoring-*,.watches,.triggered_watches,.watcher-history-*"
indices.recovery.max_bytes_per_sec: "40mb"
indices.lifecycle.poll_interval: "5m"
indices.lifecycle.history_index_enabled: true
indices.recovery.max_concurrent_file_chunks: 2
indices.recovery.max_concurrent_operations: 1

#----------------------- Performance Settings -------------
thread_pool.write.size: 32
thread_pool.search.size: 16
indices.query.bool.max_clause_count: 2048
search.max_buckets: 100000
search.default_search_timeout: "30s"
search.max_keep_alive: "24h"
search.allow_expensive_queries: false