# Kibana 8.10.0 Configuration
# Enhanced configuration for AUSTA Health Portal monitoring and visualization

#====================#
# Server Settings
#====================#
server.name: "austa-health-kibana"
server.host: "0.0.0.0"
server.port: 5601
server.publicBaseUrl: "https://kibana.austa-health.com"
server.maxPayloadBytes: 10485760

#====================#
# Elasticsearch
#====================#
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
elasticsearch.requestTimeout: 30000
elasticsearch.shardTimeout: 30000

#====================#
# Security
#====================#
xpack.security.enabled: true
xpack.security.encryptionKey: "${ENCRYPTION_KEY}"
xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "24h"

# Audit Logging
xpack.security.audit.enabled: true
xpack.security.audit.appender.type: "json_file"
xpack.security.audit.appender.path: "/var/log/kibana/audit.json"
xpack.security.audit.ignore_filters.success: false

#====================#
# Monitoring
#====================#
xpack.monitoring.enabled: true
xpack.monitoring.kibana.collection.enabled: true
xpack.monitoring.collection.interval: "15s"
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.monitoring.ui.container.logstash.enabled: true
xpack.monitoring.min_interval_seconds: 10
xpack.monitoring.show_license_expiration: true

#====================#
# Logging
#====================#
logging.root.level: "info"
logging.appenders.file.type: "file"
logging.appenders.file.fileName: "/var/log/kibana/kibana.log"
logging.appenders.file.layout.type: "json"
logging.appenders.rolling.type: "rolling_file"
logging.appenders.rolling.maxBackups: 10
logging.metrics.enabled: true

#====================#
# Internationalization
#====================#
i18n.locale: "pt-BR"
i18n.fallback: "en"

#====================#
# Telemetry
#====================#
telemetry.enabled: false
telemetry.allowChangingOptInStatus: false

#====================#
# Reporting
#====================#
xpack.reporting.enabled: true
xpack.reporting.capture.timeouts.waitForElements: 30000
xpack.reporting.csv.maxSizeBytes: 10485760
xpack.reporting.queue.timeout: "2m"
xpack.reporting.roles.enabled: true
xpack.reporting.encryptionKey: "${REPORTING_ENCRYPTION_KEY}"

#====================#
# Dashboard Settings
#====================#
xpack.dashboard.rollups.enable: true
xpack.dashboard.refresh_interval: "15s"
xpack.dashboard.max_buckets: 10000
xpack.dashboard.preserve_scroll_position: true
xpack.dashboard.autocomplete_timeout: "1000ms"
xpack.dashboard.autocomplete_suggestions: 15