# Kubernetes Secrets Encryption Configuration
# Version: 1.0.0
# Purpose: Configure envelope encryption for Kubernetes secrets using Azure Key Vault
# Compliance: LGPD and Healthcare Data Protection Requirements
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
metadata:
  name: cluster-encryption-config
  labels:
    app.kubernetes.io/name: secrets-encryption
    app.kubernetes.io/component: security
    app.kubernetes.io/managed-by: terraform
spec:
  resources:
    - resources:
        - secrets
      providers:
        # Primary encryption provider using Azure Key Vault
        - azureKeyVault:
            keyName: k8s-secrets-key
            keyVersion: current
            keyVaultURL: ${key_vault.vault_uri}
            keyRotationPeriod: 90d
            identityClientID: ${aks_cluster_identity.principal_id}
            tenantID: ${aks_cluster_identity.tenant_id}
            keyType: RSA-HSM
            keySize: 2048
            autoRotate: true
            
        # Secondary encryption provider for fallback
        - aescbc:
            keys:
              - name: fallback-key
                secret: ${FALLBACK_ENCRYPTION_KEY}
                
        # Identity provider as last resort
        - identity: {}

---
# Key Rotation Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: encryption-key-rotation-config
  namespace: kube-system
data:
  rotation-policy.yaml: |
    rotationSchedule: "0 0 1 */3 *"  # Every 90 days
    keyVaultConfig:
      vaultURL: ${key_vault.vault_uri}
      keyName: k8s-secrets-key
      keyType: RSA-HSM
      keySize: 2048
      autoRotate: true
      retentionPeriod: 180d  # Keep old keys for 180 days
    reencryptionConfig:
      batchSize: 500
      concurrentWorkers: 5
      timeoutSeconds: 3600
    notifications:
      enabled: true
      channels:
        - type: email
          recipients: ["security@austa.health"]
        - type: webhook
          url: "https://monitoring.austa.health/hooks/key-rotation"

---
# Audit Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: encryption-audit-config
  namespace: kube-system
data:
  audit-policy.yaml: |
    auditLevel: RequestResponse
    auditEvents:
      - category: encryption
        operations:
          - Rotate
          - Reencrypt
        resources:
          - group: ""
            resources: ["secrets"]
    retention:
      days: 365  # LGPD compliance requirement
    storage:
      type: azure-blob
      config:
        containerName: encryption-audit-logs
        retentionPolicy:
          enabled: true
          days: 365

---
# Health Check Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: encryption-health-config
  namespace: kube-system
data:
  health-check.yaml: |
    checks:
      - name: key-vault-connectivity
        interval: 5m
        timeout: 30s
        threshold: 3
      - name: key-rotation-status
        interval: 1h
        timeout: 5m
        threshold: 2
      - name: encryption-status
        interval: 15m
        timeout: 1m
        threshold: 3
    alerting:
      criticalThreshold: 2
      warningThreshold: 1
      notifications:
        - type: email
          recipients: ["security@austa.health"]
        - type: pagerduty
          serviceKey: ${PAGERDUTY_SERVICE_KEY}