apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "document-service.name" . }}
    helm.sh/chart: {{ include "document-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: document-system
  annotations:
    prometheus.io/scrape: {{ .Values.monitoring.enabled | default "true" | quote }}
    prometheus.io/port: {{ .Values.monitoring.metrics.port | default "8080" | quote }}
    prometheus.io/path: {{ .Values.monitoring.metrics.path | default "/metrics" | quote }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-dns-label-name: {{ include "document-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: {{ .Values.service.protocol }}
      name: http
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "document-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: service
  sessionAffinity: None
  publishNotReadyAddresses: false