apiVersion: v2
name: health-service
description: "Helm chart for AUSTA's Health Assessment and Questionnaire Service, providing dynamic health questionnaires and risk assessment capabilities"
type: application
version: 1.0.0
appVersion: 1.0.0

keywords:
  - health
  - assessment
  - questionnaire
  - fastapi
  - python
  - austa
  - healthcare

maintainers:
  - name: AUSTA Healthcare DevOps
    email: devops@austa.healthcare

dependencies:
  - name: postgresql
    version: 12.5.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache

annotations:
  artifacthub.io/changes: "Initial release of Health Service Helm chart with PostgreSQL and Redis dependencies"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/recommendations: "true"
  austa.healthcare/team: "health-service"
  austa.healthcare/tier: "backend"
  austa.healthcare/critical: "true"