apiVersion: v1
kind: Service
metadata:
  name: {{ include "policy-service.fullname" . }}
  labels:
    {{- include "policy-service.labels" . | nindent 4 }}
    service.istio.io/canonical-name: {{ include "policy-service.fullname" . }}
    service.istio.io/canonical-revision: {{ .Values.image.tag | default .Chart.AppVersion }}
    prometheus.io/scrape: {{ .Values.monitoring.enabled | default "true" | quote }}
    prometheus.io/port: {{ .Values.monitoring.port | default "8080" | quote }}
  annotations:
    sidecar.istio.io/inject: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.monitoring.port | default 8080 }}
      targetPort: {{ .Values.monitoring.targetPort | default 8080 }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "policy-service.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  publishNotReadyAddresses: false